# Credits to RethinkDNS for this starter Fly.io file.
# However I didn't find how to actually define the script to deploy...
app = ""

kill_signal = "SIGINT"
kill_timeout = 5

[env]
FORCE_IN_TLS = "tls"
FORCE_OUT_TLS = "tls"
MASK_IP = "spoof"
MASK_UA = "mimic"
MATCH_LANG = "*"
HEALTH_MAX_TRIES = 3
HEALTH_CRITERIA = "loose"
TIMEOUT_MS = 4000
IDLE_SHUTDOWN = 0

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8000
protocol = "tcp"
script_checks = []

  [services.concurrency]
  type = "connections"
  hard_limit = 80
  soft_limit = 60

  [[services.ports]]
  handlers = ["tls"]
  tls_options = { alpn = ["h2", "http/1.1"] }
  port = 443

  [[services.tcp_checks]]
  grace_period = "15s"
  interval = "60s"
  restart_limit = 5
  timeout = "5s"