name = "cloud-hop"
route = ""
type = "javascript"
account_id = ""
workers_dev = true
zone_id = ""
compatibility_date = "2022-07-16"

[build]

[build.upload]
format = "modules"
dir = "../dist"
main = "cloudflare.js"

[vars]
DEBUGGER=1
MASK_IP="mask:16:32"
MASK_UA="noBracket"
FORCE_OUT_TLS="tls"
STRIP_HEADERS_UP="Sec-Fetch-User,Sec-Fetch-Site,Sec-Fetch-Mode,Sec-Fetch-Dest"
SET_HEADERS="x-cloudhop-debug=debug"
MATCH_LANG="en_US,en,*"
HEALTH_MAX_TRIES=5
HEALTH_CRITERIA="client"
TIMEOUT_MS=4000
IDLE_SHUTDOWN=0

[env.prod.vars]
FORCE_IN_TLS="tls"
FORCE_OUT_TLS="tls"
MASK_IP="spoof"
MASK_UA="mimic"
MATCH_LANG="*"
HEALTH_MAX_TRIES=3
HEALTH_CRITERIA="loose"
TIMEOUT_MS=4000
IDLE_SHUTDOWN=0